G15 driver fixes
lcdproc/lcdproc pull request #121
Opened 2019-05-03 08:04 UTC by jwrdegoede

After testing with a G15 keyboard I noticed various corruptions of the top and bottom rows of characters when using lcdproc with the G15 LCD screen.

This pull-req contains a series of refactoring + fixes patches which fixes this.

2019-05-04 17:01 UTC, haraldg requested changes
Thanks for the cleanup and fixes!

2019-05-04 17:01 UTC, haraldg commented on server/drivers/g15.c
> +	if (p->backingstore == NULL) {
copy&paste error here

2019-05-04 17:01 UTC, haraldg commented on server/drivers/g15.c
> +	g15r_pixelReverseFill(p->canvas, px, py, px + 7, py + 7, G15_PIXEL_FILL, G15_COLOR_WHITE);
any reason you use literal 7s here instead of something involving G15_CELL_WIDTH/HEIGHT?

2019-05-08 13:55 UTC, jwrdegoede commented on server/drivers/g15.c
> +	if (p->backingstore == NULL) {
Good catch fixed for the next version.

2019-05-08 13:56 UTC, jwrdegoede commented on server/drivers/g15.c
> +	g15r_pixelReverseFill(p->canvas, px, py, px + 7, py + 7, G15_PIXEL_FILL, G15_COLOR_WHITE);
No special reason, I will switch to using G15_CELL_FOO - 1 for the next version.

2019-05-08 14:17 UTC, jwrdegoede commented
Ok, the version which I've just pushed should address all your review remarks.

2019-05-08 22:41 UTC, merged