Hd44780 ezio
lcdproc/lcdproc pull request #82
Opened 2017-05-06 20:48 UTC by fmertz

I wanted to propose a code change to add support for yet another variation of the HD44780 driver: the Portwell EZIO-100 and EZIO-300 devices. These devices come built-in some firewall appliances and have some popularity in the pfSense community.

![](https://www.portwell.com.tw/images/p_img/large/EZIO-100.jpg)

![](http://www.portwell.com/im/ca/EZIO-300-v.jpg)

Portwell put a serial interface "in front" of the LCD controller. The serial device has a couple of differences compared to other serial interfaces already implemented. The initialization sequence is "repeated", and a command has to be sent in order to receive the keypad status.

A concern is that I only own this particular EZIO-100 device, so that is the only one I can test. I therefore tried to minimize the possibility of accidentally breaking support for other devices by updating the main struct in the serial code.

The documentation is [here](http://drivers.portwell.com/CA_Manual/).

Thanks for considering this request for inclusion into the project. I will do a follow-up pull request for the updated documentation.

2017-05-06 23:48 UTC, fmertz commented
Build can be fixed with PR #83

2017-05-12 10:50 UTC, haraldg requested changes
Looks good to me, but I will only merge after Documentation has been added to the PR.

In the future I'd prefer smaller commits embodying logical changes, but no need to change this now.

2017-05-12 10:50 UTC, haraldg commented on server/drivers/hd44780-serial.c
>  				}
Coding style want's the case statement on the same indentation level as the switch statement.

2017-05-20 16:11 UTC, fmertz commented on server/drivers/hd44780-serial.c
>  				}
Another commit was provided to better comply with the coding style

2017-05-26 08:10 UTC, merged